start = expression

expression =
    WS* ex:(atom / atomlist / quote) WS*
        { return ex; }

comment =
    ";;" (WS* atom)* "\n"
        { return ''; }

quote =
    "'" ex:expression
        { return ['quote', ex]; }

atom =
    chars:validchar+
        { return chars.join(""); }

atomlist =
    "(" ex:expression* ")"
        { return ex; }

validchar = [0-9a-zA-Z_?!+-=@#$%^&*/.]
WS = ([ \t\n] / comment)
