#! /usr/bin/node

var PEG = require('pegjs');
var fs = require('fs');

fs.readFile('parser.peg', 'ascii', function(err, data) {
    // Create parser
    var parse = PEG.buildParser(data).parse;
    // Get processes
    if (process.argv.length < 3) {
        console.log("%s <file>", process.argv[1]);
    } else {
        fs.readFile(process.argv[2], 'ascii', function (err, data) {
            console.log(parse(data));
        });
    }
});
